[package]
name = "mc-link-central"
version = "0.3.2"
edition = "2021"
authors = ["棱镜Prism工作室"]
description = "MC Link 中央服务器 - 中继协调与房间管理"
license = "GPLv3"

[dependencies]
mc-link-common = { path = "../mc-link-common" }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"