[package]
name = "mc-link-chat"
version = "0.1.0"
edition = "2021"
authors = ["Cugo", "棱镜Prism工作室"]
description = "MC Link 语音服务器"

[dependencies]
mc-link-common = { path = "../mc-link-common" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
rand = "0.8"
log = "0.4"
env_logger = "0.10"
local-ip-address = "0.6"